#' Annotate motifs in regions of interest
#' 
#' Looks at instances of motifs of interest along the entire genome.
#' @param bed Bed file containing the regions you want to analyze.
#' @param genome Name of the reference genome to use. "hg19" is set as default.
#' @param motif_file Character with the path and name of the motif_file generated by 
#' catSignMotifsHOMER().
#' @param out_name Name of the output file.
#' @param path_homer Path for homer location in your computer. It automatically looks in the aliases.
#' @return It will return two files: output_file.bed, which wil contain the coordinates for the motifs analyzed and
#' output_file.tsv, which will contain the annotation information and the data of which motif was found in which region.
#' @export
#' @examples 
#' \dontrun{
#' annotateMotifsRegions(bed="regions.bed", motif_file="allMotifs.motif", out_name="myOutput")
#' }
annotateMotifsRegions <- function(bed, genome="hg19", motif_file, out_name="motifs_genome.bed", path_homer="default") {
  if (path_homer=="default") {
    path_homer=gsub("bin/homer", "", Sys.which("homer"), fixed=T)
    if (path_homer == "/") {
      stop("Could not find HOMER installation. Please provide path using argument 'path_homer'")
    }
  }
  find <- paste(paste0(path_homer, "bin/annotatePeaks.pl"),
                bed, genome,
                "-m", motif_file, 
                "-mbed", paste0(out_name, ".bed"),
                "-noann -nogene",
                ">", paste0(out_name, ".tsv")
              )
  system(find, ignore.stdout=TRUE, ignore.stderr=TRUE)
}